version: 2.1

orbs:
  slack: circleci/slack@4.9.3

jobs:
  test:
    docker:
      - image: erlang:28
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build
          command: make
      - run:
          name: Lint
          command: make lint
      - run:
          name: Dialyzer
          command: make dialyzer
      - run:
          name: Test
          command: make test
      - slack/notify:
          event: always

workflows:
  test:
    jobs:
      - test:
          context: ohr486-circleci-notification
