version: 2.1

orbs:
  slack: circleci/slack@4.9.3

jobs:
  test:
    docker:
      - image: circleci/erlang:25
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: make ci
      - slack/notify:
          event: always

workflows:
  test:
    jobs:
      - test:
          context: ohr486-circleci-notification
